CREATE TABLE IF NOT EXISTS payments (
	id UUID NULL DEFAULT NULL,
	invoice_id UUID NULL DEFAULT NULL,
	midtrans_order_id VARCHAR(255) NULL DEFAULT NULL,
	status VARCHAR(100) NULL DEFAULT NULL,
	payment_type VARCHAR(100) NULL DEFAULT NULL,
	paid_at TIMESTAMP NULL DEFAULT NULL,
	payment_url TEXT NULL DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
);